export const TUTORIAL_NEXT_STEP = "TUTORIAL_NEXT_STEP";

export const CREATION_NEXT_STEP = "CREATION_NEXT_STEP";

export const CREATION_PARTICIPANTS = "CREATION_PARTICIPANTS";

export const COMPLETED_PARTICIPANTS_SECTION = "COMPLETED_PARTICIPANTS_SECTION";

export const CREATION_CONFIG = "CREATION_CONFIG";

export const STOP_ROUND_DETAIL_LOADING = "STOP_ROUND_DETAIL_LOADING";

export const CREATION_FREQUENCY = "CREATION_FREQUENCY";

export const CREATION_TURNS = "CREATION_TURNS";

export const CREATION_AMOUNT = "CREATION_AMOUNT";

export const PICK_TURNS_MANUAL = "PICK_TURNS_MANUAL";

export const PARTICIPANTS_VISIBLE = "PARTICIPANTS_VISIBLE";

export const NEW_NUMBER_ASSIGNED = "NEW_NUMBER_ASSIGNED";

export const REMOVE_ASSIGNED_NUMBER = "REMOVE_ASSIGNED_NUMBER";

export const START_EDITING_ROUND = "START_EDITING_ROUND";

export const SET_STORED_ROUNDS = "SET_STORED_ROUNDS";

export const REMOVE_STORED_ROUND = "SET_STORED_ROUNDS";

export const GET_ROUND_DATA = "GET_ROUND_DATA";

// Request rounds
export const LOAD_ROUNDS_START = "LOAD_ROUNDS_START";
export const LOAD_ROUNDS_SUCCEEDED = "LOAD_ROUNDS_SUCCEEDED";
export const LOAD_ROUNDS_FAILED = "LOAD_ROUNDS_FAILED";

// Delete round
export const DELETEROUND_REQUEST_START = "DELETEROUND_REQUEST_START";
export const REMOVE_ROUND = "REMOVE_ROUND";
export const DELETEROUND_REQUEST_SUCCEEDED = "DELETEROUND_REQUEST_SUCCEEDED";
export const DELETEROUND_REQUEST_FAILED = "DELETEROUND_REQUEST_FAILED";
export const CREATION_DATE = "CREATION_DATE";

// Create round
export const CREATION_ROUND = "CREATION_ROUND";
export const CREATION_NAME = "CREATION_NAME";
export const CLEAR_STORE = "CLEAR_STORE";
export const CREATEROUND_REQUEST_SUCCEEDED = "CREATEROUND_REQUEST_SUCCEEDED";
export const CREATEROUND_REQUEST_FAILED = "CREATEROUND_REQUEST_FAILED";
export const CREATEROUND_REQUEST_START = "CREATEROUND_REQUEST_START";
export const CREATION_CONFIRMATION_DATE = "CREATION_CONFIRMATION_DATE";
export const CREATION_PAYMENT_DATE = "CREATION_PAYMENT_DATE";
export const SET_ROUND_FAILED_DATA = "SET_ROUND_FAILED_DATA";
export const TURN_ASSIGNMENT_MODE = "TURN_ASSIGNMENT_MODE";

// Start round
export const START_ROUND_START = "START_ROUND_START";
export const START_ROUND_SUCCEEDED = "START_ROUND_SUCCEEDED";
export const START_ROUND_FAILED = "START_ROUND_FAILED";

// Pay Round
export const PAY_ROUND = "PAY_ROUND";
export const PAY_ROUND_FAILED = "PAY_ROUND_FAILED";
export const PAY_ROUND_CLEAN = "PAY_ROUND_CLEAN";

// Close Round
export const CLOSE_ROUND = "CLOSE_ROUND";
export const CLOSE_ROUND_FAILED = "CLOSE_ROUND_FAILED";

// Swap Participant
export const SWAP_PARTICIPANT_START = "SWAP_PARTICIPANT_START";
export const SWAP_PARTICIPANT_SUCCEEDED = "SWAP_PARTICIPANT_SUCCEEDED";
export const SWAP_PARTICIPANT_FAILED = "SWAP_PARTICIPANT_FAILED";
export const SWAP_CLEAN = "SWAP_CLEAN";

// INVITATION
export const INVITATION_CLEAN = "INVITATION_CLEAN";
export const INVITATION_START = "INVITATION_START";
export const INVITATION_SUCCEEDED = "INVITATION_SUCCEEDED";
export const INVITATION_FAILED = "INVITATION_FAILED";

// Request numbers
export const REQUEST_NUMBERS_CLEAN = "REQUEST_NUMBERS_CLEAN";
export const REQUEST_NUMBERS_START = "REQUEST_NUMBERS_START";
export const REQUEST_NUMBERS_SUCCEEDED = "REQUEST_NUMBERS_SUCCEEDED";
export const REQUEST_NUMBERS_FAILED = "REQUEST_NUMBERS_FAILED";

// Remove Participant
export const REMOVE_PARTICIPANT_START = "REMOVE_PARTICIPANT_START";
export const REMOVE_PARTICIPANT_SUCCEEDED = "REMOVE_PARTICIPANT_SUCCEEDED";
export const REMOVE_PARTICIPANT_FAILED = "REMOVE_PARTICIPANT_FAILED";
export const REMOVE_CLEAN = "REMOVE_CLEAN";

// Assign Participant
export const ASSIGN_PARTICIPANT_START = "ASSIGN_PARTICIPANT_START";
export const ASSIGN_PARTICIPANT_SUCCEEDED = "ASSIGN_PARTICIPANT_SUCCEEDED";
export const ASSIGN_PARTICIPANT_FAILED = "ASSIGN_PARTICIPANT_FAILED";

// Spinner for number screen
export const START_ROUND_LOAD = "START_ROUND_LOAD";
export const END_ROUND_LOAD = "END_ROUND_LOAD";

// LOADING FOR ONBOARDING
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";

// LOADING REGISTER
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_NOT_LOADING = "REGISTER_NOT_LOADING";
export const REGISTER_FINISH = "REGISTER_FINISH";
export const SET_REGISTER_ERROR = "SET_REGISTER_ERROR";

// LOADING FOR FORGOT
export const LOADING_FORGOT = "LOADING_FORGOT";
export const FINISH_LOADING_FORGOT = "FINISH_LOADING_FORGOT";
export const CLEAN_FORGOT = "CLEAN_FORGOT";

export const LOADING_NEW_PASSWORD = "LOADING_NEW_PASSWORD";
export const FINISH_LOADING_NEW_PASSWORD = "FINISH_LOADING_NEW_PASSWORD";

// Logout
export const LOGOUT = "LOGOUT";

// Phone
export const PHONE_START_LOADING = "PHONE_START_LOADING";
export const PHONE_SUCCEDED = "PHONE_SUCCEDED";
export const PHONE_FAILED = "PHONE_FAILED";
export const PHONE_END_LOADING = "PHONE_END_LOADING";

export const PHONE_VERIFY_SUCCEDED = "PHONE_VERIFY_SUCCEDED";
export const PHONE_VERIFY_FAILED = "PHONE_VERIFY_FAILED";

export const PHONE_CLEAN = "PHONE_CLEAN";

// Charge number
export const CHARGE_NUMBER_START = "CHARGE_NUMBER_START";
export const CHARGE_NUMBER_SUCCEEDED = "CHARGE_NUMBER_SUCCEEDED";
export const CHARGE_NUMBER_FAILED = "CHARGE_NUMBER_FAILED";
export const CHARGE_NUMBER_CLEAN = "CHARGE_NUMBER_CLEAN";

// Get user data
export const START_GET_USER_DATA = "START_GET_USER_DATA";
export const GET_USER_DATA = "GET_USER_DATA";

export const ACCEPT_AND_REQUEST = "ACCEPT_AND_REQUEST";
export const ACCEPT_AND_REQUEST_CLEAN = "ACCEPT_AND_REQUEST_CLEAN";

export const OPEN_ROUND_DETAIL_ROOT_MODAL = "OPEN_ROUND_DETAIL_ROOT_MODAL";
export const CLOSE_ROUND_DETAIL_ROOT_MODAL = "CLOSE_ROUND_DETAIL_ROOT_MODAL";

// Route Options (for nested navigators)
export const SET_ROUTE_OPTIONS = "SET_ROUTE_OPTIONS";
export const GET_ROUTE_OPTIONS = "GET_ROUTE_OPTIONS";

export const START_GET_NOTIFICATIONS = "START_GET_NOTIFICATIONS";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";

export const START_FORCE_SC = "START_FORCE_SC";
export const FINISH_FORCE_SC = "FINISH_FORCE_SC";
