export const TUTORIAL_NEXT_STEP = 'TUTORIAL_NEXT_STEP';

export const CREATION_NEXT_STEP = 'CREATION_NEXT_STEP';

export const CREATION_PARTICIPANTS = 'CREATION_PARTICIPANTS';

export const CREATION_CONFIG = 'CREATION_CONFIG';

export const CREATION_AMOUNT = 'CREATION_AMOUNT';

export const LOGIN = 'LOGIN';

// Request rounds
export const LOAD_ROUNDS = 'LOAD_ROUNDS';
export const ROUNDS_REQUEST_START = 'ROUNDS_REQUEST_START';

// Delete round
export const DELETEROUND_REQUEST_START = 'DELETEROUND_REQUEST_START';
export const REMOVE_ROUND = 'REMOVE_ROUND';
export const DELETEROUND_REQUEST_SUCCEEDED = 'DELETEROUND_REQUEST_SUCCEEDED';
export const DELETEROUND_REQUEST_FAILED = 'DELETEROUND_REQUEST_FAILED';
export const CREATION_DATE = 'CREATION_DATE';

// Create round
export const CREATION_ROUND = 'CREATION_ROUND';
export const CREATION_NAME = 'CREATION_NAME';
export const CLEAR_STORE = 'CLEAR_STORE';
export const CREATEROUND_REQUEST_SUCCEEDED = 'CREATEROUND_REQUEST_SUCCEEDED';
export const CREATEROUND_REQUEST_FAILED = 'CREATEROUND_REQUEST_FAILED';
export const CREATEROUND_REQUEST_START = 'CREATEROUND_REQUEST_START';
export const CREATION_CONFIRMATION_DATE = 'CREATION_CONFIRMATION_DATE';
export const CREATION_PAYMENT_DATE = 'CREATION_PAYMENT_DATE';

// Start round
export const START_ROUND_START = 'START_ROUND_START';
export const START_ROUND_SUCCEEDED = 'START_ROUND_SUCCEEDED';
export const START_ROUND_FAILED = 'START_ROUND_FAILED';

// Pay Round
export const PAY_ROUND = 'PAY_ROUND';

// Close Round
export const CLOSE_ROUND = "CLOSE_ROUND"

// Swap Participant
export const SWAP_PARTICIPANT_START = 'SWAP_PARTICIPANT_START';
export const SWAP_PARTICIPANT_SUCCEEDED = 'SWAP_PARTICIPANT_SUCCEEDED';
export const SWAP_PARTICIPANT_FAILED = 'SWAP_PARTICIPANT_FAILED';
export const SWAP_CLEAN = 'SWAP_CLEAN';

// Spinner for number screen
export const START_ROUND_LOAD = 'START_ROUND_LOAD';
export const END_ROUND_LOAD = 'END_ROUND_LOAD';
