export const TUTORIAL_NEXT_STEP = 'TUTORIAL_NEXT_STEP';

export const CREATION_NEXT_STEP = 'CREATION_NEXT_STEP';

export const CREATION_PARTICIPANTS = 'CREATION_PARTICIPANTS';

export const CREATION_CONFIG = 'CREATION_CONFIG';

export const CREATION_AMOUNT = 'CREATION_AMOUNT';

// Request rounds
export const LOAD_ROUNDS_START = 'LOAD_ROUNDS_START';
export const LOAD_ROUNDS_SUCCEEDED = 'LOAD_ROUNDS_SUCCEEDED';
export const LOAD_ROUNDS_FAILED = 'LOAD_ROUNDS_FAILED';

// Delete round
export const DELETEROUND_REQUEST_START = 'DELETEROUND_REQUEST_START';
export const REMOVE_ROUND = 'REMOVE_ROUND';
export const DELETEROUND_REQUEST_SUCCEEDED = 'DELETEROUND_REQUEST_SUCCEEDED';
export const DELETEROUND_REQUEST_FAILED = 'DELETEROUND_REQUEST_FAILED';
export const CREATION_DATE = 'CREATION_DATE';

// Create round
export const CREATION_ROUND = 'CREATION_ROUND';
export const CREATION_NAME = 'CREATION_NAME';
export const CLEAR_STORE = 'CLEAR_STORE';
export const CREATEROUND_REQUEST_SUCCEEDED = 'CREATEROUND_REQUEST_SUCCEEDED';
export const CREATEROUND_REQUEST_FAILED = 'CREATEROUND_REQUEST_FAILED';
export const CREATEROUND_REQUEST_START = 'CREATEROUND_REQUEST_START';
export const CREATION_CONFIRMATION_DATE = 'CREATION_CONFIRMATION_DATE';
export const CREATION_PAYMENT_DATE = 'CREATION_PAYMENT_DATE';

// Start round
export const START_ROUND_START = 'START_ROUND_START';
export const START_ROUND_SUCCEEDED = 'START_ROUND_SUCCEEDED';
export const START_ROUND_FAILED = 'START_ROUND_FAILED';

// Pay Round
export const PAY_ROUND = 'PAY_ROUND';
export const PAY_ROUND_FAILED = 'PAY_ROUND_FAILED';

// Close Round
export const CLOSE_ROUND = "CLOSE_ROUND"
export const CLOSE_ROUND_FAILED = "CLOSE_ROUND_FAILED"

// Swap Participant
export const SWAP_PARTICIPANT_START = 'SWAP_PARTICIPANT_START';
export const SWAP_PARTICIPANT_SUCCEEDED = 'SWAP_PARTICIPANT_SUCCEEDED';
export const SWAP_PARTICIPANT_FAILED = 'SWAP_PARTICIPANT_FAILED';
export const SWAP_CLEAN = 'SWAP_CLEAN';

// INVITATION
export const INVITATION_CLEAN = 'INVITATION_CLEAN';
export const INVITATION_START = 'INVITATION_START';
export const INVITATION_SUCCEEDED = 'INVITATION_SUCCEEDED';
export const INVITATION_FAILED = 'INVITATION_FAILED';

// Request numbers
export const REQUEST_NUMBERS_CLEAN = 'REQUEST_NUMBERS_CLEAN';
export const REQUEST_NUMBERS_START = 'REQUEST_NUMBERS_START';
export const REQUEST_NUMBERS_SUCCEEDED = 'REQUEST_NUMBERS_SUCCEEDED';
export const REQUEST_NUMBERS_FAILED = 'REQUEST_NUMBERS_FAILED';


// Remove Participant
export const REMOVE_PARTICIPANT_START = 'REMOVE_PARTICIPANT_START';
export const REMOVE_PARTICIPANT_SUCCEEDED = 'REMOVE_PARTICIPANT_SUCCEEDED';
export const REMOVE_PARTICIPANT_FAILED = 'REMOVE_PARTICIPANT_FAILED';
export const REMOVE_CLEAN = 'REMOVE_CLEAN';

// Assign Participant
export const ASSIGN_PARTICIPANT_START = 'ASSIGN_PARTICIPANT_START';
export const ASSIGN_PARTICIPANT_SUCCEEDED = 'ASSIGN_PARTICIPANT_SUCCEEDED';
export const ASSIGN_PARTICIPANT_FAILED = 'ASSIGN_PARTICIPANT_FAILED';

// Spinner for number screen
export const START_ROUND_LOAD = 'START_ROUND_LOAD';
export const END_ROUND_LOAD = 'END_ROUND_LOAD';


//LOADING FOR ONBOARDING
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGIN_FAILED = "LOGIN_FAILED"

//LOADING REGISTER
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_NOT_LOADING = "REGISTER_NOT_LOADING";
export const REGISTER_FINISH = "REGISTER_FINISH"
//LOADING FOR FORGOT
export const LOADING_FORGOT = "LOADING_FORGOT"
export const FINISH_LOADING_FORGOT = "FINISH_LOADING_FORGOT"
export const CLEAN_FORGOT = "CLEAN_FORGOT";


export const LOADING_NEW_PASSWORD = "LOADING_NEW_PASSWORD";
export const FINISH_LOADING_NEW_PASSWORD = "FINISH_LOADING_NEW_PASSWORD"

