version: "3.3"
services:
  api:
    build:
      context: ./
    image: ronda-api-dev
    container_name: ronda-api
    depends_on:
      - mongodb
    environment:
      - PORT=${PORT}
      - ENVIROMENT=${ENVIROMENT}
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
      - CIPHER_KEY=${CIPHER_KEY}
      - CIPHER_ALGORITHM=${CIPHER_ALGORITHM}
      - SALT_STRING=${SALT_STRING}
      - INPUT_ENCODING=${INPUT_ENCODING}
      - OUTPUT_ENCODING=${OUTPUT_ENCODING}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_SERVER=${MONGO_SERVER}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTHTOKEN=${TWILIO_AUTHTOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - ENABLE_SC_FEATURES=${ENABLE_SC_FEATURES}
      - ENABLE_SWAGGER=${ENABLE_SWAGGER}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_ENCODED_AUTH=${MAILGUN_ENCODED_AUTH}
      - RONDA_RNS_SUBDOMAIN=${RONDA_RNS_SUBDOMAIN}
      - DEFAULT_ADDRESS=${DEFAULT_ADDRESS}
      - RSK_ENDPOINT=${RSK_ENDPOINT}
      - WEB3_NODE_LOCATION=${WEB3_NODE_LOCATION}
      - RNS_NODE_LOCATION=${RNS_NODE_LOCATION}
      - CHAIN_ID=${CHAIN_ID}
      - GAS_PRICE_HEX=${GAS_PRICE_HEX}
      - STORAGE_HOST=${STORAGE_HOST}
      - STORAGE_PORT=${STORAGE_PORT}
      - RONDA_CONTRACT_OWNER=${RONDA_CONTRACT_OWNER}
      - RONDA_CONTRACT_OWNER_PK=${RONDA_CONTRACT_OWNER_PK}
      - RONDA_REGISTRY_ADDRESS=${RONDA_REGISTRY_ADDRESS}
      - PUBLIC_RESOLVER_ADDRESS=${PUBLIC_RESOLVER_ADDRESS}
      - RNS_RESOLVER_ADDRESS=${RNS_RESOLVER_ADDRESS}
      - RNS_ADDRESS=${RNS_ADDRESS}
      - REFILL_SECONDS=${REFILL_SECONDS}
      - REFILL_MINUTES=${REFILL_MINUTES}
      - REFILL_HOURS=${REFILL_HOURS}
      - REFILL_DAY_OF_MONTH=${REFILL_DAY_OF_MONTH}
      - REFILL_MONTH=${REFILL_MONTH}
      - REFILL_DAY_OF_WEEL=${REFILL_DAY_OF_WEEL}
      - WALLET_TARGET_BALANCE=${WALLET_TARGET_BALANCE}
      - WALLET_MIN_BALANCE=${WALLET_MIN_BALANCE}
      - REFILL_ORIGIN_ACCOUNT=${REFILL_ORIGIN_ACCOUNT}
      - REFILL_ORIGIN_ACCOUNT_PK=${REFILL_ORIGIN_ACCOUNT_PK}
      - DIDI_SERVER=${DIDI_SERVER}
      - DID=${DID}
      - PRIVATE_KEY=${PRIVATE_KEY}
    networks:
      - ronda
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${CONFIG_DIR}:/configs

  mongodb:
    image: mongo:4.4.0
    container_name: ronda-api-mongodb
    volumes:
      - ${VOLUME_DIR}/db-data:/data/db
      - ${VOLUME_DIR}/configs:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ronda
    ports:
      - 27017:27017

networks:
  ronda:
    driver: bridge
